"""
Configuration module for Crab Simulator
Centralized control over physics parameters, leg mappings, and gait settings
"""

# ============================================================================
# SAND/GROUND PHYSICS - Granular Resistive Force Theory (RFT)
# ============================================================================
# These values simulate Upper Dry Beach Sand behavior
# Reference: README.md mass calculation = 2.09 kg → ~2.7 cm sinkage at equilibrium

SAND_CONFIG = {
    # Vertical stiffness (N/m) - controls how rigid the sand feels
    # Higher = harder sand (less sinkage), Lower = softer sand (more sinkage)
    'K_VERTICAL': 180.0,
    
    # Horizontal drag coefficient (N·s/m) - controls lateral resistance
    # Higher = more resistance to horizontal motion (sticky sand)
    # Lower = less resistance (loose sand)
    'K_HORIZONTAL': 25.0,
    
    # Penetration threshold (m) - depth at which RFT forces start applying
    # Typically 0 (forces apply when z < 0, i.e., below ground plane)
    'PENETRATION_THRESHOLD': 0.01,
}

# ============================================================================
# LEG CONTROL MAPPING
# ============================================================================
# Maps dactyl tips (sensors) to dactyl bodies (where forces are applied).

LEG_TIPS = {
    'tip_rf': {'body': 'dactyl_rf', 'name': 'Right Front',  'active': True},
    'tip_rb': {'body': 'dactyl_rb', 'name': 'Right Back',   'active': True},
    'tip_rm': {'body': 'dactyl_rm', 'name': 'Right Middle', 'active': True},
    'tip_lf': {'body': 'dactyl_lf', 'name': 'Left Front',   'active': True},
    'tip_lb': {'body': 'dactyl_lb', 'name': 'Left Back',    'active': True},
    'tip_lm': {'body': 'dactyl_lm', 'name': 'Left Middle',  'active': True},
}

# ============================================================================
# TRIPOD GAIT PHASE OFFSETS
# ============================================================================
# Two tripods, 180° out of phase. Each tripod is two opposite corners + the
# opposing middle leg, forming a stable support triangle:
#   Tripod A (offset 0.0): left-front, left-back, right-middle
#   Tripod B (offset 0.5): right-front, right-back, left-middle
LEG_PHASE_OFFSETS = {
    'tip_lf': 0.0,
    'tip_lb': 0.0,
    'tip_rm': 0.0,
    'tip_rf': 0.5,
    'tip_rb': 0.5,
    'tip_lm': 0.5,
}

# ============================================================================
# PARAMETRIC GAIT — amplitudes & timing
# ============================================================================
# Foot trajectory is generated by a continuous function of cycle phase, then
# converted to (knee, ankle) angles.  Side sign flips the angles for left vs
# right legs so right legs push UNDER the chassis while left legs pull OUTSIDE.
#
#   STANCE (phase ∈ [0, DUTY))  — foot planted, sweeping (drives the body)
#   SWING  (phase ∈ [DUTY, 1))  — foot lifted, returning forward
#
# Tune KNEE_STRIDE / ANKLE_STRIDE for stride length, KNEE_CLEAR for lift height.

GAIT_CONFIG = {
    'cycle_duration':  4.0,   # seconds per full gait cycle
    'duty':            0.5,   # stance fraction (0.5 = symmetric tripod)
    'hip_target':      0.0,   # hip held neutral — stride comes from knee+ankle
    'warmup_duration': 2.0,   # seconds to blend in from neutral standing pose

    # Home pose — side-signed.  Right legs sit at +home (tucked under chassis),
    # left legs at -home (splayed outside).  Without this offset, opposite-side
    # opposite-phase legs collapse to the same joint angle and the tripod
    # symmetry breaks (all corners look identical, both middles look identical).
    'knee_home':    0.5,      # how far the leg is tucked under / splayed out at rest
    'ankle_home':   -0.1,      # ankle curl at rest

    # Cycling amplitudes — added on top of home pose
    'knee_stride':  0.6,      # knee swing during stance (push/pull strength)
    'knee_clear':   1.0,      # knee opening during swing (ground clearance)
    'ankle_stride': -0.2,      # ankle contribution to stride
    'ankle_tuck':   0.6,      # ankle curl during swing
}

# ============================================================================
# SIMULATION PARAMETERS
# ============================================================================

SIMULATION_CONFIG = {
    # Render the visualization
    'use_viewer': True,
    
    # Print debug information during simulation
    'verbose': True,
    
    # Log forces and states for analysis
    'log_forces': False,
    'log_file': 'simulation_log.csv',
}

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_active_legs():
    """Returns list of active leg tip names"""
    return [tip_name for tip_name, info in LEG_TIPS.items() if info['active']]

def get_leg_body(tip_name):
    """Returns the body name for a given tip sensor"""
    if tip_name in LEG_TIPS:
        return LEG_TIPS[tip_name]['body']
    return None

def activate_leg(leg_name):
    """Enable control for a specific leg"""
    if leg_name in LEG_TIPS:
        LEG_TIPS[leg_name]['active'] = True

def deactivate_leg(leg_name):
    """Disable control for a specific leg"""
    if leg_name in LEG_TIPS:
        LEG_TIPS[leg_name]['active'] = False

def activate_all_legs():
    """Enable all 6 legs (for multi-leg control in future)"""
    for leg in LEG_TIPS:
        LEG_TIPS[leg]['active'] = True

def deactivate_all_legs():
    """Disable all legs"""
    for leg in LEG_TIPS:
        LEG_TIPS[leg]['active'] = False
