"""
Gait Controller Module — Parametric tripod gait

Foot motion is generated by continuous functions of cycle phase, not
keyframes.  Each leg shares the same math; only its phase offset (which
tripod it belongs to) and side sign (left vs right joint mirroring) differ.
"""

import numpy as np
import config


class GaitController:
    """Parametric tripod gait — one math expression per leg, no keyframes."""

    def __init__(self, gait_params=None):
        if gait_params is None:
            gait_params = config.GAIT_CONFIG

        self.cycle_duration  = gait_params.get('cycle_duration', 4.0)
        self.duty            = gait_params.get('duty', 0.5)
        self.hip_target      = gait_params.get('hip_target', 0.0)
        self.warmup_duration = gait_params.get('warmup_duration', 2.0)

        # Side-signed home pose
        self.knee_home    = gait_params.get('knee_home',    0.5)
        self.ankle_home   = gait_params.get('ankle_home',   0.3)

        # Cycling amplitudes
        self.knee_stride  = gait_params.get('knee_stride',  0.6)
        self.knee_clear   = gait_params.get('knee_clear',   1.0)
        self.ankle_stride = gait_params.get('ankle_stride', 0.4)
        self.ankle_tuck   = gait_params.get('ankle_tuck',   0.5)

    # ------------------------------------------------------------------ #
    # Phase math
    # ------------------------------------------------------------------ #
    def get_phase_info(self, sim_time):
        """Return phase index (0=STANCE, 1=SWING), progress within phase,
        cycle progress, and a printable name."""
        wrapped = sim_time % self.cycle_duration
        progress = wrapped / self.cycle_duration         # 0..1

        if progress < self.duty:
            phase_index   = 0
            phase_name    = 'STANCE'
            time_in_phase = progress / self.duty
        else:
            phase_index   = 1
            phase_name    = 'SWING'
            time_in_phase = (progress - self.duty) / (1.0 - self.duty)

        return {
            'phase_index':    phase_index,
            'phase_name':     phase_name,
            'time_in_phase':  time_in_phase,
            'cycle_progress': progress,
            'current_time':   wrapped,
        }

    # ------------------------------------------------------------------ #
    # Foot trajectory  →  joint angles
    # ------------------------------------------------------------------ #
    def _foot_trajectory(self, progress):
        """progress ∈ [0,1)  →  (reach ∈ [-1,1], lift ∈ [0,1])

        reach = +1 extended forward (in walking direction)
        reach = -1 tucked back
        lift  = 0 on the ground, peaks at 1 mid-swing
        """
        if progress < self.duty:
            # STANCE — foot planted, sweeping +1 → -1 (this propels the body)
            s = progress / self.duty
            return 1.0 - 2.0 * s, 0.0
        else:
            # SWING — foot airborne, returning -1 → +1 with a smooth lift bell
            s = (progress - self.duty) / (1.0 - self.duty)
            return -1.0 + 2.0 * s, np.sin(np.pi * s)

    def _leg_targets(self, progress, side_sign):
        """Convert foot trajectory into (knee, ankle) joint angles for one leg.

        side_sign = +1 (right): joints positive → leg tucks UNDER chassis (push)
        side_sign = -1 (left):  joints negative → leg reaches OUTSIDE chassis (pull)

        The side-signed *_home terms keep the leg on its own side of the body at
        rest.  Without them, a leg that's 180° out of phase on the opposite side
        ends up at the same joint angle (the two negations cancel) — that's the
        bug that made all four corners look identical.
        """
        reach, lift = self._foot_trajectory(progress)

        knee  = ( self.knee_home  + self.knee_stride  * reach  -  self.knee_clear * lift) * side_sign
        ankle = ( self.ankle_home + self.ankle_stride * reach  +  self.ankle_tuck * lift) * side_sign
        return knee, ankle

    # ------------------------------------------------------------------ #
    # Top-level entry point used by simulate_crab.py
    # ------------------------------------------------------------------ #
    def compute_joint_targets(self, sim_time):
        """Return {joint_name: target_angle} for every active leg."""
        warmup_blend = self._smooth_step(min(sim_time / self.warmup_duration, 1.0))

        targets = {}
        for leg_name, leg_info in config.LEG_TIPS.items():
            if not leg_info['active']:
                continue

            leg_id    = leg_name.replace('tip_', '')
            side_sign = +1.0 if leg_id.startswith('r') else -1.0
            offset    = config.LEG_PHASE_OFFSETS.get(leg_name, 0.0)

            # Each leg's clock is shifted by its tripod's phase offset
            leg_time  = sim_time + offset * self.cycle_duration
            progress  = (leg_time % self.cycle_duration) / self.cycle_duration

            knee, ankle = self._leg_targets(progress, side_sign)

            # Warmup: blend from 0 (neutral standing) into the full gait so the
            # robot doesn't get launched by an instantaneous torque spike at t=0.
            targets[f'hip_{leg_id}']   = self.hip_target
            targets[f'knee_{leg_id}']  = knee  * warmup_blend
            targets[f'ankle_{leg_id}'] = ankle * warmup_blend

        return targets

    @staticmethod
    def _smooth_step(t):
        """Cosine ease-in/ease-out — zero velocity at both endpoints."""
        return (1.0 - np.cos(np.pi * t)) / 2.0

    # ------------------------------------------------------------------ #
    # Runtime tweaks & debug
    # ------------------------------------------------------------------ #
    def set_gait_parameters(self, **kwargs):
        """Update any amplitude or timing parameter at runtime."""
        for key, value in kwargs.items():
            if hasattr(self, key) and value is not None:
                setattr(self, key, value)

    def print_status(self, sim_time):
        print(f"\n=== Gait Status (t={sim_time:.2f}s) ===")
        print(f"Cycle: {self.cycle_duration}s   Duty: {self.duty:.2f}   "
              f"Warmup: {self.warmup_duration}s")
        print(f"Home  knee={self.knee_home}  ankle={self.ankle_home}")
        print(f"Stride  knee={self.knee_stride}  ankle={self.ankle_stride}   "
              f"Swing  knee_clear={self.knee_clear}  ankle_tuck={self.ankle_tuck}")
        for leg_name, leg_info in config.LEG_TIPS.items():
            if not leg_info['active']:
                continue
            offset   = config.LEG_PHASE_OFFSETS.get(leg_name, 0.0)
            leg_time = sim_time + offset * self.cycle_duration
            pi       = self.get_phase_info(leg_time)
            print(f"  {leg_info['name']:14s} (offset={offset:.1f}) → "
                  f"{pi['phase_name']:6s} {pi['time_in_phase']*100:5.1f}%")
        print("=====================================\n")
